### PR TITLE
Add Azure services PostgreSQL flexible, Recovery Vault & Backup Vault

### LINKED ISSUE #191: Add PostgreSQL flexible to Azure services list
Hello,

Azure PostgreSQL flexible "Microsoft.DBforPostgreSQL/flexibleServers" is not in the supported Azure services list.

### PR DESCRIPTION
**Pull request by BzSpi**
Hello,

This PR adds the PostgreSQL flexible, Recovery Vault & Backup Vault services to the supported Azure services list.

Closes #191 #192 #193

### CODE REVIEW

**Comment by BzSpi** [comment]
References:
* https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftdbforpostgresqlflexibleservers
* https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftdataprotectionbackupvaults
* https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftrecoveryservicesvaults

**Comment by bgola-signalfx** [comment]
Please note this change requires similar change on the Splunk Observability backend side. I am going to take care of that and merge this PR afterwards.

**Comment by BzSpi** [comment]
Hello @bgola-signalfx 
Any chance to have this library updated in the [Terraform provider](https://github.com/splunk-terraform/terraform-provider-signalfx) ?

**Comment by bgola-signalfx** [comment]
@BzSpi Just FYI, we run into some dependency conflicts and we need to postpone the release. We will keep you posted.

**Comment by akonarska** [comment]
@BzSpi The new version of terraform-provider is up with those changes https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v7.0.0

**Pull request merged**
